name: Python CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: setup-python
          uses: actions/setup-python@v2
        - name: install1
          run:  pip install poetry
        - name: install2
          run: make install
        - name: run-linter
          run:  make lint
        - name: run tests
          run: make result_stylish
        - name: result_stylish & publish code coverage
          uses: paambaati/codeclimate-action@v3.0.0
          env:
            CC_TEST_REPORTER_ID: ${{ secrets.COVERAGE_ID }}
          with:
            coverageCommand: make result_stylish-coverage
            debug: true